# Generated by Django 3.1.7 on 2021-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210328_1322"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthDate",
            field=models.DateTimeField(
                blank=True, max_length=128, null=True, verbose_name="Birth date"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="userType",
            field=models.CharField(
                choices=[("Landlord", "Landlord"), ("Tenant", "Tenant")],
                default="Tenant",
                max_length=30,
                verbose_name="User type",
            ),
        ),
    ]
