# Generated by Django 3.1.7 on 2021-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20210329_0755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="userType",
            field=models.CharField(
                blank=True,
                choices=[("LANDLORD", "LANDLORD"), ("TENANT", "TENANT")],
                default="TENANT",
                max_length=30,
                verbose_name="User type",
            ),
        ),
    ]
